// Written in D programming language
/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module gui.AddBaseTab;

import gtk.Box;
import gtk.Notebook;
import gtk.Label;
import gtk.Alignment;
import gtk.Entry;
import gtk.Button;
import gtk.TreeModel;
import gtk.TreePath;
import gtk.TreeViewColumn;
import gtk.TreeIter;

import gui.TableView;

import data.structure;
import data.wrapper;

import orm.orm;

class AddBaseTab : Box
{
	struct AddFormInfo
	{
		Entry[string] entries;
		Button submitBtn;
	}
	AddFormInfo[string] addForms;

	SharksDB db;

	this(SharksDB db)
	{
		super(GtkOrientation.VERTICAL, 5);
		this.db = db;

		packStart(initTablesTabs(), true, true, false);
	}

	protected
	{
		Notebook initTablesTabs()
		{
			auto tabs = new Notebook();
			foreach(i, type; SharksDBTables)
			{
				tabs.appendPage(createAddForm!(SharksDBTableNames[i], SharksDBTablesColumnNames[i]), SharksDBTableNames[i]);
			}
			return tabs;
		}

		Box createAddForm(TableNameAndColNames...)()
		{
			auto box = new Box(GtkOrientation.HORIZONTAL, 5);
			auto labelBox = new Box(GtkOrientation.VERTICAL, 8);
			auto entryBox = new Box(GtkOrientation.VERTICAL, 5);
			box.packStart(labelBox, false, false, false);
			box.packStart(entryBox, true, true, false);

			AddFormInfo info;
			foreach(i, name; TableNameAndColNames[1])
			{
				labelBox.packStart(new Label(name), false, false, false);

				auto entry = new Entry("");
				entryBox.packStart(entry, false, false, false);
				info.entries[name] = entry;
			}

			auto btnBox = new Box(GtkOrientation.HORIZONTAL, 5);
			auto submitBtn = new Button("Добавить");
			info.submitBtn = submitBtn;
			btnBox.packStart(submitBtn, true, true, false);

			labelBox.add(btnBox);
			addForms[TableNameAndColNames[0]] = info;
			return box;			
		}
	}
}