// Written in D programming language
/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module gui.TableView;

import std.datetime;
import std.conv;
import std.traits;
import gtk.TreeView;
import gtk.TreeViewColumn;
import gtk.CellRendererText;
import gui.CustomList;
import util.common;


private template GenStringFields(rnames...)
{
	enum names = rnames[0];
	static if(names.length == 0)
		enum GenStringFields = "";
	else
		enum GenStringFields = "string "~names[0]~";\n"~GenStringFields!(names[1..$]);
}

private template StructWrapper(Aggregate)
{
	static assert(isAggregateType!Aggregate);
	private alias FieldNameTuple!(Aggregate) fieldNames;
	private alias TypeTupleFrom!(Aggregate, fieldNames) fieldTypes;

	class RowRecord
	{	
		uint pos;
		mixin(GenStringFields!(fieldNames));

		this()
		{

		}

		this(Aggregate data)
		{
			foreach(i, type; fieldTypes)
			{
				static if(is(type == Date))
					mixin("this."~fieldNames[i]~" = data."~fieldNames[i]~".toISOExtString();");
				else static if(is(type == string))
					mixin("this."~fieldNames[i]~" = data."~fieldNames[i]~";");
				else
					mixin("this."~fieldNames[i]~" = to!string(data."~fieldNames[i]~");");
			}
				
		}

		/**
		*	To acces Aggregate fields without knowing actual field name.
		*/
		string getValue(size_t i)()
		{
			return mixin(fieldNames[i]);
		}
	}	
}

class TableView(Aggregate): CustomList!(StructWrapper!(Aggregate).RowRecord)
{
	alias StructWrapper!(Aggregate).RowRecord RowRecord;
	alias CustomList!(RowRecord) ListBase;
	alias ListBase.Column Column;
	private alias FieldNameTuple!(Aggregate) fieldNames;
	private alias TypeTupleFrom!(Aggregate, fieldNames) fieldTypes;


	alias Aggregate[] delegate() DataGetter;
	//private DataGetter dataGetter;

	TreeView createTreeView(columnTitles...)()
	{
		static assert(columnTitles[0].length == fieldTypes.length);

		TreeViewColumn   col;
		CellRendererText renderer;
		TreeView         view;
		
		view = new TreeView(this);

		foreach(i, type; fieldTypes)
		{
			col = new TreeViewColumn();
			renderer = new CellRendererText();
			col.packStart(renderer, true);
			col.addAttribute(renderer, "text", mixin("Column."~fieldNames[i]));
			col.setTitle(columnTitles[0][i]);
			view.appendColumn(col);
		}

		return view;
	}

	void updateAllData(DataGetter dataGetter)
	{
		assert(dataGetter !is null);
		
		auto data = dataGetter();
		foreach(ref record; data)
		{
			appendRecord(new RowRecord(record));
		}
	}
}
