import gtk.MainWindow;
import gtk.AboutDialog;
import gtk.Notebook;
import gtk.MenuBar;
import gtk.Menu;
import gtk.MenuItem;
import gtk.Label;
import gtk.Button;
import gtk.VBox;
import gtk.Fixed;
import gtk.Main;
import gtk.Box;

private import stdlib = core.stdc.stdlib : exit;

import orm.orm;
import data;

class ButtonUsage : MainWindow
{
	Label StatusLbl;
	this()
	{
		super("Lab1");
		setDefaultSize(512, 512);
		
		MenuBar menuBar = new MenuBar();
		Menu fileMenu = menuBar.append("File");;
		MenuItem exitItem = new MenuItem((item) {stdlib.exit(0);}, "Выход");
		fileMenu.append(exitItem);
		 

		Box box = new Box(GtkOrientation.VERTICAL, 5);
		box.packStart(menuBar, 0, 0, 0);
		//box.add(menuBar);

		Box viewBox = new Box(GtkOrientation.VERTICAL, 5);

		
		StatusLbl = new Label("Click a Button");
		viewBox.add(StatusLbl);
		viewBox.add(new Button("Button 1", &onBtn1));
		viewBox.add(new Button("Exit", &onBtn2));
		viewBox.add(new Button("About", &onBtn3));

		Notebook tabs = new Notebook();
		tabs.appendPage(viewBox, "Просмотр книг");
		box.add(tabs);

		add(box);
		showAll();	
	}
	void onBtn1(Button button)
	{
		StatusLbl.setText("You Clicked Button 1");
	}
	void onBtn2(Button button)
	{
		stdlib.exit(0);
	}
	void onBtn3(Button button)
	{
		with (new AboutDialog())
		{
			string[] names;
			names ~= "Гуща Антон (NCrashed)";
			setAuthors(names);
			setComments("Первая лабораторная работа по курсу 'Банки данных'");
			setLicense(license);
			setCopyright("©Гуща А.В. 2013");
			//setWebsite("http://ddev.ratedo.com");
			showAll();
		}
	}
}

DataBase!"testbd" db;

void main(string[] args)
{
	Main.init(args);
	new ButtonUsage();
	db = new DataBase!"testbd"("host=localhost port=5432 dbname=postgres user=postgres password=150561");
	//generateBase(db, 100, 20, 100);
	Main.run();
}

string license = q{
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
};