import gtk.MainWindow;
import gtk.AboutDialog;
import gtk.Notebook;
import gtk.MenuBar;
import gtk.Menu;
import gtk.MenuItem;
import gtk.Label;
import gtk.Button;
import gtk.Main;
import gtk.Box;
import gtk.ComboBoxText;
import gtk.TreeView;

import BookList;
import gtk.ScrolledWindow;

private import stdlib = core.stdc.stdlib : exit;

import orm.orm;
import data;

import std.conv;

class Lab13Window : MainWindow
{
	BookList bookList, bookBySubjList;

	this()
	{
		super("Lab1-3");
		setDefaultSize(512, 512);

		Box box = new Box(GtkOrientation.VERTICAL, 5);
		box.packStart(initMenu(), 0, 0, 0);
		//box.add(menuBar);

		Notebook tabs = new Notebook();
		tabs.appendPage(initBookViewTab(), 		"Просмотр книг");
		tabs.appendPage(initOutViewTab(), 		"Выдача книг");
		tabs.appendPage(initInViewTab(), 		"Прием книг");
		tabs.appendPage(initHistoryViewTab(), 	"История выдачи");
		box.packStart(tabs, 1, 1, 0);

		add(box);
		showAll();	
	}

	MenuBar initMenu()
	{
		MenuBar menuBar = new MenuBar();
		Menu fileMenu = menuBar.append("Файл");
		MenuItem generateItem = new MenuItem(&onGenerate, "Регенерация базы");
		MenuItem aboutItem = new MenuItem(&onAbout, "О программе");
		MenuItem exitItem = new MenuItem((item) {stdlib.exit(0);}, "Выход");
		
		fileMenu.append(generateItem);
		fileMenu.append(aboutItem);
		fileMenu.append(exitItem);
		return menuBar;
	}

	Box initBookViewTab()
	{
		Box viewBox = new Box(GtkOrientation.VERTICAL, 5);
		ScrolledWindow scrollwin = new ScrolledWindow();
		viewBox.packStart(scrollwin, true, true, 0);
		
		bookList = new BookList;
		fillBookList(bookList);
		TreeView view = bookList.createTreeView();
		scrollwin.add(view);
		return viewBox;
	}

	Box initOutViewTab()
	{
		Box viewBox = new Box(GtkOrientation.VERTICAL, 5);
		auto outBookCombo = new ComboBoxText(false);
		viewBox.packStart(outBookCombo, false, false, 0);

		auto subjs = getAllSubjects(db);
		foreach(i, subj; subjs)
		{
			outBookCombo.append(to!string(i), subj.subject);
		}

		Box horBox = new Box(GtkOrientation.HORIZONTAL, 5);
		viewBox.packStart(horBox, true, true, 0);

		auto scrollwin = new ScrolledWindow();
		horBox.packStart(scrollwin, true, true, 10);

		bookBySubjList = new BookList;
		auto treeView = bookBySubjList.createTreeView();
		scrollwin.add(treeView);
		
		outBookCombo.addOnChanged((combo){fillBookBySubjList(bookBySubjList, combo.getActiveText());});
		return viewBox;
	}

	Box initInViewTab()
	{
		Box viewBox = new Box(GtkOrientation.VERTICAL, 5);

		return viewBox;
	}

	Box initHistoryViewTab()
	{
		Box viewBox = new Box(GtkOrientation.VERTICAL, 5);

		return viewBox;
	}

	void onGenerate(MenuItem item)
	{
		generateBase(db, 100, 20, 100);
	}

	void onAbout(MenuItem item)
	{
		with (new AboutDialog())
		{
			string[] names;
			names ~= "Гуща Антон (NCrashed)";
			setAuthors(names);
			setComments("Первая лабораторная работа по курсу 'Банки данных'");
			setLicense(license);
			setCopyright("©Гуща А.В. 2013");
			//setWebsite("http://ddev.ratedo.com");
			showAll();
		}
	}

	void fillBookList(BookList list)
	{
		list.clear();
		try
		{
			Book[] books = getAllBooks(db);

			list.fillData(books, db);
		} catch(Exception e)
		{
			import std.stdio;
			writeln(e.msg);
		}
	}	

	void fillBookBySubjList(BookList list, string subj)
	{
		if(subj is null) return;

		list.clear();
		try
		{
			Book[] books = getBooksBySubj(db, subj);
			
			list.fillData(books, db);
		} catch(Exception e)
		{
			import std.stdio;
			writeln(e.msg);
		}
	}
}

Lab13DB db;

void main(string[] args)
{
	Main.init(args);
	db = new DataBase!"testbd"("host=localhost port=5432 dbname=postgres user=postgres password=150561");

	new Lab13Window();
	
	Main.run();
}

string license = q{
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
};